/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SheltersRouteImport } from './routes/shelters'
import { Route as MapRouteImport } from './routes/map'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as AiCommandRouteImport } from './routes/ai-command'
import { Route as IndexRouteImport } from './routes/index'

const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SheltersRoute = SheltersRouteImport.update({
  id: '/shelters',
  path: '/shelters',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCommandRoute = AiCommandRouteImport.update({
  id: '/ai-command',
  path: '/ai-command',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-command': typeof AiCommandRoute
  '/incidents': typeof IncidentsRoute
  '/map': typeof MapRoute
  '/shelters': typeof SheltersRoute
  '/sos': typeof SosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-command': typeof AiCommandRoute
  '/incidents': typeof IncidentsRoute
  '/map': typeof MapRoute
  '/shelters': typeof SheltersRoute
  '/sos': typeof SosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-command': typeof AiCommandRoute
  '/incidents': typeof IncidentsRoute
  '/map': typeof MapRoute
  '/shelters': typeof SheltersRoute
  '/sos': typeof SosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-command' | '/incidents' | '/map' | '/shelters' | '/sos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-command' | '/incidents' | '/map' | '/shelters' | '/sos'
  id:
    | '__root__'
    | '/'
    | '/ai-command'
    | '/incidents'
    | '/map'
    | '/shelters'
    | '/sos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiCommandRoute: typeof AiCommandRoute
  IncidentsRoute: typeof IncidentsRoute
  MapRoute: typeof MapRoute
  SheltersRoute: typeof SheltersRoute
  SosRoute: typeof SosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelters': {
      id: '/shelters'
      path: '/shelters'
      fullPath: '/shelters'
      preLoaderRoute: typeof SheltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-command': {
      id: '/ai-command'
      path: '/ai-command'
      fullPath: '/ai-command'
      preLoaderRoute: typeof AiCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiCommandRoute: AiCommandRoute,
  IncidentsRoute: IncidentsRoute,
  MapRoute: MapRoute,
  SheltersRoute: SheltersRoute,
  SosRoute: SosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
