/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiCommandRouteImport } from './routes/ai-command'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as MapRouteImport } from './routes/map'
import { Route as PublicRouteImport } from './routes/public'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SheltersRouteImport } from './routes/shelters'
import { Route as SosRouteImport } from './routes/sos'
import { Route as TeamsRouteImport } from './routes/teams'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCommandRoute = AiCommandRouteImport.update({
  id: '/ai-command',
  path: '/ai-command',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SheltersRoute = SheltersRouteImport.update({
  id: '/shelters',
  path: '/shelters',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-command': typeof AiCommandRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/incidents': typeof IncidentsRoute
  '/map': typeof MapRoute
  '/public': typeof PublicRoute
  '/resources': typeof ResourcesRoute
  '/shelters': typeof SheltersRoute
  '/sos': typeof SosRoute
  '/teams': typeof TeamsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-command': typeof AiCommandRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/incidents': typeof IncidentsRoute
  '/map': typeof MapRoute
  '/public': typeof PublicRoute
  '/resources': typeof ResourcesRoute
  '/shelters': typeof SheltersRoute
  '/sos': typeof SosRoute
  '/teams': typeof TeamsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-command': typeof AiCommandRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/incidents': typeof IncidentsRoute
  '/map': typeof MapRoute
  '/public': typeof PublicRoute
  '/resources': typeof ResourcesRoute
  '/shelters': typeof SheltersRoute
  '/sos': typeof SosRoute
  '/teams': typeof TeamsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-command'
    | '/alerts'
    | '/analytics'
    | '/incidents'
    | '/map'
    | '/public'
    | '/resources'
    | '/shelters'
    | '/sos'
    | '/teams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-command'
    | '/alerts'
    | '/analytics'
    | '/incidents'
    | '/map'
    | '/public'
    | '/resources'
    | '/shelters'
    | '/sos'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/ai-command'
    | '/alerts'
    | '/analytics'
    | '/incidents'
    | '/map'
    | '/public'
    | '/resources'
    | '/shelters'
    | '/sos'
    | '/teams'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiCommandRoute: typeof AiCommandRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  IncidentsRoute: typeof IncidentsRoute
  MapRoute: typeof MapRoute
  PublicRoute: typeof PublicRoute
  ResourcesRoute: typeof ResourcesRoute
  SheltersRoute: typeof SheltersRoute
  SosRoute: typeof SosRoute
  TeamsRoute: typeof TeamsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-command': {
      id: '/ai-command'
      path: '/ai-command'
      fullPath: '/ai-command'
      preLoaderRoute: typeof AiCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public': {
      id: '/public'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelters': {
      id: '/shelters'
      path: '/shelters'
      fullPath: '/shelters'
      preLoaderRoute: typeof SheltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiCommandRoute: AiCommandRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  IncidentsRoute: IncidentsRoute,
  MapRoute: MapRoute,
  PublicRoute: PublicRoute,
  ResourcesRoute: ResourcesRoute,
  SheltersRoute: SheltersRoute,
  SosRoute: SosRoute,
  TeamsRoute: TeamsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
