/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AiCommandRouteImport } from './routes/ai-command'
import { Route as IndexRouteImport } from './routes/index'

const AiCommandRoute = AiCommandRouteImport.update({
  id: '/ai-command',
  path: '/ai-command',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-command': typeof AiCommandRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-command': typeof AiCommandRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-command': typeof AiCommandRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-command'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-command'
  id: '__root__' | '/' | '/ai-command'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiCommandRoute: typeof AiCommandRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ai-command': {
      id: '/ai-command'
      path: '/ai-command'
      fullPath: '/ai-command'
      preLoaderRoute: typeof AiCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiCommandRoute: AiCommandRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
